# Generated by Django 5.0.1 on 2025-01-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='block',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='blockimage',
            name='block',
        ),
        migrations.RemoveField(
            model_name='blockimage',
            name='created_by',
        ),
        migrations.RemoveIndex(
            model_name='biography',
            name='content_bio_order_3ce109_idx',
        ),
        migrations.AddField(
            model_name='publication',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='BlockImage',
        ),
    ]
