# Generated by Django 5.0.1 on 2025-01-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_publication_content_publication_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='featured_image',
            field=models.ImageField(upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
