# Generated by Django 5.0.1 on 2025-01-25 17:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_publication_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
