# Generated by Django 5.0.1 on 2025-01-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_publication_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content',
        ),
    ]
